### ISSUE TITLE
API prompt 401 

### ISSUE THREAD

**Issue by xiaozheqiu** [civitai/civitai-javascript#1]
I tried running the example nextjs-txt2img
Then replaced the. env file but still prompted 401
I don't know where the problem is

<img width="1054" alt="image" src="https://github.com/civitai/civitai-javascript/assets/49509790/213369bb-1070-425a-8c34-a493897f1f59">

**Comment by bryantanjw** [comment]
Hey! You're supposed to populate the `CIVITAI_API_TOKEN` env variable with an actual API token. We are working to allow users to generate their API tokens very soon! Apologies for the inconvenience.

I'll keep you posted!!

**Comment by xiaozheqiu** [comment]
> 嘿！您应该使用实际的 API 令牌填充 CIVITAI_API_TOKEN 环境变量。我们正在努力让用户尽快生成他们的 API 令牌！不便之处敬请原谅。
> 
> 我会及时向大家发布！！

Thank you very much for your reply, but that's what I'm doing now...

<img width="1113" alt="image" src="https://github.com/civitai/civitai-javascript/assets/49509790/7fd76b7f-93ff-4882-bd48-f27f220381dc">

<img width="787" alt="image" src="https://github.com/civitai/civitai-javascript/assets/49509790/02787540-92ce-4b29-866b-0becf9b505c6">

The key output by the console is also correct
This key is the one I generated from my Civitai account

**Comment by xiaozheqiu** [comment]
Teacher, did I do something wrong...

**Comment by bryantanjw** [comment]
Could you show/paste the full input body of the request? I'll attempt to recreate it.

By the way, you should rotate your API token for security, haha.

**Comment by xiaozheqiu** [comment]
Okay, wait a moment. I'll do it now
By the way, I'm really sorry to bother you now...

**Comment by xiaozheqiu** [comment]
![image](https://github.com/civitai/civitai-javascript/assets/49509790/f24498f0-2170-47db-845c-956f9b08be74)
Is it the information on the picture

**Comment by xiaozheqiu** [comment]
> Could you show/paste the full input body of the request? I'll attempt to recreate it.
> 
> By the way, you should delete the image with your API token for security, haha.

I will delete this key later and create another one 😄

**Comment by bryantanjw** [comment]
Okay, I just tried to generate images with your API token. I'm pretty sure the issue here is your **type of API token**. The API token generated on your Civitai profile is for the Civitai REST API; it won't work in this SDK as your token is used for retrieving assets from the Civitai site.

You'll have to wait until we allow users to generate API tokens that can work with the SDK :(. It'll be soon though!!

**Comment by xiaozheqiu** [comment]
Really? I'm really looking forward to it. Thank you very much. Due to my limited computer hardware, I am unable to deploy the model, so I really hope to use the key to call the API to generate it, even if it requires payment

**Comment by bryantanjw** [comment]
I can relate -- I run a Mac machine 🥲. Do you usually run your worfklows/generations using ComfyUI, AUTOMATIC1111, or others? Cause we are adding ComfyUI support to the SDK soon if that interests you too :D

**Comment by xiaozheqiu** [comment]
In fact, I haven't understood the software you mentioned yet. 😄
I am a front-end developer and I may be looking for a REST API similar to OpenAI that allows me to directly request it
I don't know if you can understand what I'm saying..

**Comment by xiaozheqiu** [comment]
Or can you tell me how to obtain the key for the civitai JavaScript project
I can't find a way

**Comment by bryantanjw** [comment]
我们暂时还没有增加让用户生成他们的 SDK API token 的功能。应该下个礼拜就推出这个功能。届时，我会更新这个 issue 😄

**Comment by bryantanjw** [comment]
@xiaozheqiu 您可以尝试再用您的 API token 吗？`Unauthorized error` 应该被解决了

**Comment by xiaozheqiu** [comment]
> @xiaozheqiu 您可以尝试再用您的 API token 吗？`Unauthorized error` 应该被解决了

好的我试试，真的没想到您还会说中文 哈哈

**Comment by xiaozheqiu** [comment]
![image](https://github.com/civitai/civitai-javascript/assets/49509790/e0b9a2a6-467d-4fcc-9971-aa8d35124ae4)
我刚重新拉取了代码，确实没有 Unauthorized error 的错误了 但是好像还有其他的问题，我尝试调用api发现还是无法请求成功，并且报错

**Comment by bryantanjw** [comment]
运行 `git pull`. 我更改了一些SDK method. 最新的包版本`civitai@0.1.8`应该解决您的问题。[4e240ca05d499b9385238b43986006deca866251](https://github.com/civitai/civitai-javascript/commit/4e240ca05d499b9385238b43986006deca866251)

哈哈 我本身从马来西亚被带大的， 所以会说些中文 :D

**Comment by xiaozheqiu** [comment]
天哪 我刚重新尝试了一下 真的运行起来了 感谢感谢😄

**Comment by xiaozheqiu** [comment]
真的感谢你的帮助，我本想使用twitter关注你并且给你发消息，但是我不太会使用twitter，您可以给我提供一个其他的联系方式吗
不过您帮我解决了这个问题，我想给您买杯咖啡表示感谢，希望不要拒绝😄

**Comment by bryantanjw** [comment]
我熟悉twitter或discord @bryantanjw。若有问题，可在那联系。 但最好是在这开Issue。

哈哈 没这个需要，这是我普通责任啊！

**Comment by xiaozheqiu** [comment]
我在twitter关注了你 不过不知道为什么似乎无法与您对话，可能我们国家不怎么使用这个软件吧...
哈哈 真的是对您的帮忙表示感谢，我还是很乐意为我的知识付费的，当然我也会继续努力的😄
