### ISSUE TITLE
请问这个模型可以从civitai获取吗 我不知道怎么做

### ISSUE THREAD

**Issue by xiaozheqiu** [civitai/civitai-javascript#3]
![image](https://github.com/civitai/civitai-javascript/assets/49509790/3b0181d9-5af7-498e-8e32-53e1cf325e90)

**Comment by zenafey** [comment]
You can find it on civitai by air id

https://civitai.com/models/4201/130072

It's realistic vision 5.1

**Comment by xiaozheqiu** [comment]
thanks... 

<img width="851" alt="image" src="https://github.com/civitai/civitai-javascript/assets/49509790/6ac73571-e664-452e-a475-2b245e747682">

May I ask if this prefix is fixed
Is it only necessary to replace the following model ID...

**Comment by zenafey** [comment]
i dont know what about other than "sd1" models but for them(i guess its any SD 1.5 finetune) yes, you just can replace ID

**Comment by xiaozheqiu** [comment]
<img width="1416" alt="image" src="https://github.com/civitai/civitai-javascript/assets/49509790/f8728121-ef13-407a-aadb-1e0b8bc7f6f1">

[](https://civitai.com/models/248011/astranime)


I tried to replace the model ID from this link and use it in the project, but the effect I saw was that I kept requesting the interface and did not return the corresponding image. Is it because I used it incorrectly

**Comment by xiaozheqiu** [comment]
https://civitai.com/models/248011/astranime

This link is the model ID I just used

**Comment by zenafey** [comment]
You used text name of version instead of AIR ID, you can find it here, like on screenshot
![image](https://github.com/civitai/civitai-javascript/assets/118455214/bed36a8c-9f7c-4d7d-8770-e438ff619f0a)

**Comment by xiaozheqiu** [comment]
Haha, it seems like I did another foolish thing. Forgive me for just getting into Stable Diffusion😄

**Comment by bryantanjw** [comment]
> You used text name of version instead of AIR ID, you can find it here, like on screenshot ![image](https://private-user-images.githubusercontent.com/118455214/310913252-bed36a8c-9f7c-4d7d-8770-e438ff619f0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4Mzc2MDQsIm5iZiI6MTcwOTgzNzMwNCwicGF0aCI6Ii8xMTg0NTUyMTQvMzEwOTEzMjUyLWJlZDM2YThjLTlmN2MtNGQ3ZC04NzcwLWU0MzhmZjYxOWYwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxODQ4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGQxNDYwYzdjNjRlMTg5MDY2Nzg5N2UwOTYwOWI0Y2JlY2ZjNmMxMDU2ZGMwNGQxMjJiNDlhYzdmMTQ3ZTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2k8qRLoDHfo7eDHQZCVTzsR792QsUCSIFv0hOn_wLN8)

@xiaozheqiu to be able to view the AIR for models, you'll have to toggle on AI Resource Identifier on *Account settings*.
<img width="652" alt="toggle air" src="https://github.com/civitai/civitai-javascript/assets/34775928/d372c8f1-a42f-4ef4-848a-9a7a86c050a9">

Worth noting that generating images with models that are not cached in our workers will take a while :(

**Comment by xiaozheqiu** [comment]
I understand, but I have one more question
Civitai's API provides some interfaces, such as https://civitai.com/api/v1/models
May I ask if it is possible to obtain similar model information in this API
![image](https://github.com/civitai/civitai-javascript/assets/49509790/f4237901-6232-4eaf-b48a-2a5745f0a571)

By the way, how do I pay for the token I am currently using

**Comment by bryantanjw** [comment]
Unfortunately, you can't get the model information using the SDK just like how you could with the Civitai REST API.

In regards to the cost of using your API tokens for the SDK,  **we don't currently charge for usage — but have plans to do so soon**. We do currently have rate limit moderation in place to prevent abuse.

**Comment by zenafey** [comment]
> Unfortunately, you can't get the model information using the SDK just like how you could with the Civitai REST API.
> 
> In regards to the cost of using your API tokens for the SDK,  **we don't currently charge for usage — but have plans to do so soon**. We do currently have rate limit moderation in place to prevent abuse.

will there be a free plan?

**Comment by bryantanjw** [comment]
It will eventually cost [buzz](https://education.civitai.com/civitais-guide-to-buzz-%E2%9A%A1/) to use the SDK/Civitai Cloud to create jobs, so you could get them buzz for free by participating in the community 🤝🫂. There will potentially be programs, e.g., accelerators, to help new projects get off the ground by providing them free buzz for use in the SDK, too!
