### ISSUE TITLE
Does it support running in browser?

### ISSUE THREAD

**Issue by hxgqh** [civitai/civitai-javascript#6]
Does it support running in browser?

**Comment by bryantanjw** [comment]
I'm assuming you're asking about PWA capabilities. The SDK is designed to interact with Civitai's backend services to generate images. The generations using GPU resources, is done on Civitai's servers, not on the client-side (i.e., in the browser). It does not support using browser directly for generations; it's used within a browser environment to send requests to our servers that handles the generations.
